// File: data/products.ts
'use client'
import { Product } from "./types";

// Expanded Groceries Data (20 items)
export const groceries: Product[] = [
  {
    id: "1",
    name: "Argan Shampoo",
    category: "Grocery",
    image: "/grocery/arganShampoo.jpeg",
    price:  500,
    rating: 4.5,
    description: "Revitalize your hair with organic Argan oil shampoo.",
  },
  {
    id: "2",
    name: "Assorted Coffee",
    category: "Grocery",
    image: "/grocery/Assorted Coffe.jpeg",
    price: 200,
    rating: 4.0,
    description: "A selection of premium coffees from around the world.",
  },
  {
    id: "3",
    name: "Milk",
    category: "Dairy",
    image: "/Dairy/Milk.jpeg",
    price: 100,
    rating: 3.5,
    description: "Fresh, organic milk straight from the farm.",
  },
  {
    id: "4",
    name: "Avocado Oil",
    category: "Grocery",
    image: "/grocery/Avocado oil.jpg",
    price: 50,
    rating: 4.2,
    description: "Cold-pressed avocado oil for healthy cooking.",
  },
  {
    id: "5",
    name: "Natural Extracted Edible Oil",
    category: "Grocery",
    image: "/grocery/Natural Extracted Edible oil.jpg",
    price: 250,
    rating: 4.7,
    description: "Pure, natural extracted oil for all your cooking needs.",
  },
  {
    id: "6",
    name: "Handwash",
    category: "Grocery",
    image: "/grocery/handwash.jpeg",
    price: 150,
    rating: 4.3,
    description: "Gentle handwash with a refreshing fragrance.",
  },
  {
    id: "7",
    name: "Cheese",
    category: "Dairy",
    image: "/Dairy/cheese.jpeg",
    price: 350,
    rating: 4.6,
    description: "Rich, creamy farm-made cheese for every meal.",
  },
  {
    id: "8",
    name: "Almonds",
    category: "Grocery",
    image: "/grocery/almond.jpeg",
    price: 300,
    rating: 4.8,
    description: "Healthy and crunchy organic almonds for snacking.",
  },
  {
    id: "9",
    name: "Body Lotion",
    category: "Grocery",
    image: "/grocery/bodylotion.jpg",
    price: 180,
    rating: 4.4,
    description: "Nourishing body lotion for soft, moisturized skin.",
  },
  {
    id: "10",
    name: "Yogurt",
    category: "Dairy",
    image: "/Dairy/yogurt.jpeg",
    price: 120,
    rating: 4.1,
    description: "Creamy, probiotic-rich yogurt for a healthy diet.",
  },
  {
    id: "11",
    name: "Corn Flakes",
    category: "Grocery",
    image: "/grocery/cornflicks.jpeg",
    price: 450,
    rating: 4.6,
    description: "Crispy and delicious corn flakes for breakfast.",
  },
  {
    id: "12",
    name: "Face Wash",
    category: "Grocery",
    image: "/grocery/facewash.jpg",
    price: 60,
    rating: 4.2,
    description: "Gentle face wash to keep your skin clean and fresh.",
  },
  {
    id: "13",
    name: "Butter",
    category: "Dairy",
    image: "/Dairy/butter.jpeg",
    price: 200,
    rating: 4.4,
    description: "Rich, creamy butter for your toast and baking needs.",
  },
  {
    id: "14",
    name: "Chia Seeds",
    category: "Grocery",
    image: "/grocery/chia seeds.jpeg",
    price: 300,
    rating: 4.7,
    description: "Nutritious organic chia seeds for smoothies and baking.",
  },
  {
    id: "15",
    name: "Green Chilli",
    category: "Grocery",
    image: "/grocery/greenchilli.jpg",
    price: 100,
    rating: 4.3,
    description: "Spicy fresh green chillies for your favorite dishes.",
  },
  {
    id: "16",
    name: "Peanut Butter",
    category: "Grocery",
    image: "/grocery/peanut butter.jpeg",
    price: 350,
    rating: 4.8,
    description: "Creamy, natural peanut butter for spreads and cooking.",
  },
  {
    id: "17",
    name: "Hand Sanitizer",
    category: "Grocery",
    image: "/grocery/Hand Sanitizer.jpg",
    price: 550,
    rating: 4.9,
    description: "Antibacterial hand sanitizer to keep germs at bay.",
  },
  {
    id: "18",
    name: "Hersheys",
    category: "Grocery",
    image: "/grocery/hersheys.jpeg",
    price: 80,
    rating: 4.2,
    description: "Rich, creamy Hersheys chocolate syrup for desserts.",
  },
  {
    id: "19",
    name: "Ketchup",
    category: "Grocery",
    image: "/grocery/ketchup.jpg",
    price: 750,
    rating: 4.6,
    description: "Tangy tomato ketchup to enhance the taste of your food.",
  },
  {
    id: "20",
    name: "Khajoor",
    category: "Grocery",
    image: "/grocery/Khajoor.jpg",
    price: 150,
    rating: 4.7,
    description: "Sweet, organic dates rich in nutrients.",
  },
  {
    id: "21",
    name: "Masoor Dal",
    category: "Grocery",
    image: "/grocery/masoordal.jpg",
    price: 100,
    rating: 4.7,
    description: "Nutritious and protein-rich Masoor dal.",
  },
  {
    id: "22",
    name: "Moong Dal",
    category: "Grocery",
    image: "/grocery/moongdal.jpg",
    price: 200,
    rating: 4.7,
    description: "Healthy and organic Moong dal for a protein-rich diet.",
  },
  {
    id: "23",
    name: "Oats",
    category: "Grocery",
    image: "/grocery/oats.jpg",
    price: 250,
    rating: 4.7,
    description: "Whole grain oats for a healthy and filling breakfast.",
  },
  {
    id: "24",
    name: "Salt",
    category: "Grocery",
    image: "/grocery/salt.jpeg",
    price: 30,
    rating: 4.7,
    description: "Pure, fine salt to enhance the flavor of your meals.",
  },
  {
    id: "25",
    name: "Shampoo",
    category: "Grocery",
    image: "/grocery/shampoo.jpeg",
    price: 120,
    rating: 4.7,
    description: "Gentle shampoo for daily hair care.",
  },
  {
    id: "26",
    name: "Soap",
    category: "Grocery",
    image: "/grocery/soap.jpeg",
    price: 80,
    rating: 4.7,
    description: "Natural, organic soap for soft and clean skin.",
  },
  {
    id: "27",
    name: "Tea",
    category: "Grocery",
    image: "/grocery/Tea.jpeg",
    price: 200,
    rating: 4.7,
    description: "Refreshing and aromatic tea leaves for a relaxing brew.",
  },
  {
    id: "28",
    name: "Toor Dal",
    category: "Grocery",
    image: "/grocery/ToorDal.jpg",
    price: 100,
    rating: 4.7,
    description: "Organic Toor dal, perfect for protein-packed meals.",
  },
];


// Expanded Juice Data (20 items)
export const juices: Product[] = [
  {
    id: "1",
    name: "Apple Juice",
    category: "Fruits",
    image: "/juice/Apple Juice.jpeg",
    price: 500,
    rating: 4.5,
    description: "Freshly pressed apple juice.",
  },
  {
    id: "2",
    name: "Banana Juice",
    category: "Fruits",
    image: "/juice/banana juice.jpg",
    price: 200,
    rating: 4.0,
    description: "Delicious banana juice made from ripe bananas.",
  },
  {
    id: "3",
    name: "Carrot Juice",
    category: "Vegetables",
    image: "/juice/carrot.jpeg",
    price: 150,
    rating: 4.1,
    description: "Nutritious carrot juice packed with vitamins.",
  },
  {
    id: "4",
    name: "Orange Juice",
    category: "Fruits",
    image: "/juice/orange juice.jpg",
    price: 350,
    rating: 4.7,
    description: "Freshly squeezed orange juice.",
  },
  {
    id: "5",
    name: "Mango Juice",
    category: "Fruits",
    image: "/juice/freshMangoJuice.jpg",
    price: 400,
    rating: 4.6,
    description: "Sweet and refreshing mango juice.",
  },
  {
    id: "6",
    name: "Pineapple Juice",
    category: "Fruits",
    image: "/juice/pineapple juice.jpeg",
    price: 300,
    rating: 4.5,
    description: "Tropical and tangy pineapple juice.",
  },
  {
    id: "7",
    name: "Mixed Berry Juice",
    category: "Fruits",
    image: "/juice/cranberry.jpeg",
    price: 450,
    rating: 4.8,
    description: "A blend of fresh berries in a delicious juice.",
  },
  {
    id: "8",
    name: "Grape Juice",
    category: "Fruits",
    image: "/juice/grape Juice.jpeg",
    price: 400,
    rating: 4.4,
    description: "Rich and flavorful grape juice.",
  },
  {
    id: "9",
    name: "Watermelon Juice",
    category: "Fruits",
    image: "/juice/watermelon.jpeg",
    price: 300,
    rating: 4.7,
    description: "Refreshing watermelon juice, perfect for summer.",
  },
  {
    id: "10",
    name: "Pomegranate Juice",
    category: "Fruits",
    image: "/juice/pomegranate.jpeg",
    price: 550,
    rating: 4.9,
    description: "Antioxidant-rich pomegranate juice.",
  },
  {
    id: "11",
    name: "Lemon Juice",
    category: "Fruits",
    image: "/juice/lemon.jpeg",
    price: 100,
    rating: 4.3,
    description: "Freshly squeezed lemon juice, great for drinks.",
  },
  {
    id: "12",
    name: "Tomato Juice",
    category: "Vegetables",
    image: "/juice/tomato juice.jpeg",
    price: 180,
    rating: 4.1,
    description: "Nutritious tomato juice full of flavor.",
  },
  {
    id: "13",
    name: "Beetroot Juice",
    category: "Vegetables",
    image: "/juice/beetroot.jpeg",
    price: 250,
    rating: 4.6,
    description: "Rich and healthy beetroot juice.",
  },
  {
    id: "14",
    name: "Cucumber Juice",
    category: "Vegetables",
    image: "/juice/cucumber.jpeg",
    price: 140,
    rating: 4.2,
    description: "Refreshing and cooling cucumber juice.",
  },
  {
    id: "15",
    name: "Guava Juice",
    category: "Fruits",
    image: "/juice/guava.jpeg",
    price: 400,
    rating: 4.5,
    description: "Tropical and sweet guava juice.",
  },
  {
    id: "16",
    name: "Pear Juice",
    category: "Fruits",
    image: "/juice/pear.jpeg",
    price: 350,
    rating: 4.3,
    description: "Mildly sweet and smooth pear juice.",
  },
  {
    id: "17",
    name: "Papaya Juice",
    category: "Fruits",
    image: "/juice/papaya.jpeg",
    price: 300,
    rating: 4.1,
    description: "Creamy and rich papaya juice.",
  },
  {
    id: "18",
    name: "Kiwi Juice",
    category: "Fruits",
    image: "/juice/kiwi.jpeg",
    price: 450,
    rating: 4.4,
    description: "Tangy and exotic kiwi juice.",
  },
  {
    id: "19",
    name: "Cranberry Juice",
    category: "Fruits",
    image: "/juice/cranberry.jpeg",
    price: 500,
    rating: 4.8,
    description: "Tart and antioxidant-packed cranberry juice.",
  },
  {
    id: "20",
    name: "Tangerine Juice",
    category: "Fruits",
    image: "/juice/Tangerine.jpeg",
    price: 350,
    rating: 4.6,
    description: "Citrusy and tangy tangerine juice.",
  },
];

// Expanded Products Data (20 items)
export const products: Product[] = [
  {
    id: '1',
    name: 'Banana',
    category: 'Fruits',
    image: '/fruits/banana.jpeg',
    price: 82,
    rating: 4.5,
    originalPrice: 99,
    isOnSale: true,
    description: 'Fresh bananas full of nutrients, perfect for a quick snack. Only ₹82 per dozen.',
  },
  {
    id: "2",
    image: "/grocery/Hand Sanitizer.jpg",
    category: "Grocery",
    name: "Hand Sanitizer",
    price: 150,
    rating: 3,
    description: "Keep your hands clean and germ-free. 500ml for ₹1250.",
  },
  {
    id: "3",
    image: "/vegetables/chillies.jpeg",
    category: "Vegetables",
    name: "Handpicked Red Chillies",
    price: 60,
    rating: 5,
    description: "Spicy handpicked red chillies, perfect for adding heat to your dishes. 1kg for ₹1600.",
  },
  {
    id: "4",
    image: "/grocery/edible oil.jpeg",
    category: "Grocery",
    name: "Natural Extracted Edible Oil",
    price:750,
    originalPrice: 550,
    isOnSale: true,
    rating: 3,
    description: "Pure, naturally extracted oil for healthy cooking. 1 liter at ₹2100 (was ₹2850).",
  },
  {
    id: "5",
    image: "/vegetables/potatoes.jpeg",
    category: "Vegetables",
    name: "Potatoes",
    price: 40,
    rating: 4.7,
    description: "Fresh organic potatoes, direct from the farm. 5kg for ₹840.",
  },
  {
    id: "6",
    image: "/grocery/Basmati rice.jpeg",
    category: "Grocery",
    name: "Basmati Rice",
    price: 850,
    rating: 4.8,
    description: "Premium long-grain basmati rice with a fragrant aroma. 5kg for ₹3360.",
  },
  {
    id: "7",
    image: "/Dairy/egg.jpeg",
    category: "Dairy",
    name: "Free Range Eggs",
    price: 420,
    rating: 4.6,
    description: "High-quality free-range eggs, perfect for a healthy breakfast. 12 eggs for ₹420.",
  },
  {
    id: "8",
    image: "/grocery/soap.jpeg",
    category: "Grocery",
    name: "Soap",
    price: 1000,
    rating: 4.3,
    description: "Organic, chemical-free soap for gentle skincare. 1 bar for ₹1000.",
  },
  {
    id: "9",
    image: "/grocery/Tea.jpeg",
    category: "Grocery",
    name: "Green Tea",
    price: 1680,
    rating: 4.9,
    description: "Refreshing and healthy green tea leaves. 250g for ₹1680.",
  },
  {
    id: "10",
    image: "/vegetables/tomatoes.jpg",
    category: "Vegetables",
    name: "Organic Tomatoes",
    price: 588,
    rating: 4.5,
    description: "Fresh organic tomatoes, perfect for salads and cooking. 1kg for ₹588.",
  },
  {
    id: "11",
    image: "/Dairy/Milk.jpeg",
    category: "Dairy",
    name: "Milk",
    price: 210,
    rating: 4.3,
    description: "Fresh organic milk from grass-fed cows. 1 liter for ₹210.",
  },
  {
    id: "12",
    image: "/Vegetables/palak.jpeg",
    category: "Vegetables",
    name: "Palak",
    price: 252,
    rating: 4.8,
    description: "Fresh palak (spinach), rich in iron. 500g for ₹252.",
  },
  {
    id: "13",
    image: "/grocery/chia seeds.jpeg",
    category: "Grocery",
    name: "Chia Seeds",
    price: 420,
    rating: 4.9,
    description: "Nutrient-rich chia seeds for a healthy diet. 200g for ₹420.",
  },
  {
    id: "14",
    image: "/vegetables/lettuce.jpeg",
    category: "Vegetables",
    name: "Lettuce",
    price: 168,
    rating: 4.6,
    description: "Crisp, fresh organic lettuce. 1 head for ₹168.",
  },
  {
    id: "15",
    image: "/grocery/almond milk.jpeg",
    category: "Dairy",
    name: "Almond Milk",
    price: 252,
    rating: 4.5,
    description: "Nutritious and creamy almond milk. 1 liter for ₹252.",
  },
  {
    id: "16",
    image: "/grocery/whole wheat pasta.jpeg",
    category: "Grocery",
    name: "Whole Wheat Pasta",
    price: 336,
    rating: 4.2,
    description: "Healthy whole wheat pasta for a delicious meal. 500g for ₹336.",
  },
  {
    id: "17",
    image: "/grocery/Extra virgin olive oil.jpeg",
    category: "Grocery",
    name: "Extra Virgin Olive Oil",
    price: 840,
    rating: 4.7,
    description: "Premium cold-pressed extra virgin olive oil. 500ml for ₹840.",
  },
  {
    id: "18",
    image: "/vegetables/pumpkin.jpeg",
    category: "Vegetables",
    name: "Pumpkin",
    price: 252,
    rating: 4.4,
    description: "Fresh, sweet organic pumpkin. 1kg for ₹252.",
  },
  {
    id: "19",
    image: "/grocery/brown sugar.jpeg",
    category: "Grocery",
    name: "Organic Brown Sugar",
    price: 420,
    rating: 4.6,
    description: "Rich and flavorful organic brown sugar. 1kg for ₹420.",
  },
  {
    id: "20",
    image: "/fruits/fresh mangoes.jpeg",
    category: "Fruits",
    name: "Fresh Mangoes",
    price: 252,
    rating: 4.9,
    description: "Juicy and ripe fresh mangoes. 1kg for ₹252.",
  },
  {
    id: "21",
    image: "/fruits/black_grapes.jpeg",
    category: "Fruits",
    name: "Black Grapes",
    price: 252,
    rating: 4.9,
    description: "Sweet, fresh black grapes. 1kg for ₹252.",
  },
  {
    id: "22",
    image: "/fruits/watermelon.jpeg",
    category: "Fruits",
    name: "Watermelon",
    price: 252,
    rating: 4.9,
    description: "Fresh, juicy watermelon. 1kg for ₹252.",
  },
  {
    id: "23",
    image: "/fruits/grapes.jpeg",
    category: "Fruits",
    name: "Grapes",
    price: 252,
    rating: 4.9,
    description: "Fresh, juicy grapes. 1kg for ₹252.",
  },
  {
    id: "24",
    image: "/fruits/oranges.jpeg",
    category: "Fruits",
    name: "Oranges",
    price: 252,
    rating: 4.9,
    description: "Fresh, sweet oranges. 1kg for ₹252.",
  },
  {
    id: "25",
    image: "/fruits/pinapple.jpeg",
    category: "Fruits",
    name: "Pineapple",
    price: 252,
    rating: 4.9,
    description: "Fresh, sweet pineapples. 1 whole pineapple for ₹252.",
  },
  {
    id: "26",
    image: "/fruits/apples.jpeg",
    category: "Fruits",
    name: "Apples",
    price: 252,
    rating: 4.9,
    description: "Crisp, fresh apples. 1kg for ₹252.",
  },
];


// Category definitions remain the same
interface Category {
  id: string;
  name: 'Fruits' | 'Vegetables' | 'Groceries';
  image: string;
  description?: string;
}

export const categories: Category[] = [
  {
      id: '1',
      name: 'Fruits',
      image: '/images/fruits.jpg',
      description: 'Fresh and organic fruits'
  },
  {
      id: '2',
      name: 'Vegetables',
      image: '/images/vegetables.jpg',
      description: 'Organic and farm-fresh vegetables'
  },
  {
      id: '3',
      name: 'Groceries',
      image: '/images/groceries.jpg',
      description: 'All your grocery needs'
  }
];
