// File: data/products.ts
'use client'
import { Product } from "./types";

// Expanded Groceries Data (20 items)
export const groceries: Product[] = [
  {
    id: "1",
    name: "Argan Shampoo",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642285/gk4uqkv7qxavllojsvlx.jpg",
    price:  500,
    rating: 4.5,
    description: "Revitalize your hair with organic Argan oil shampoo.",
  },
  {
    id: "2",
    name: "Assorted Coffee",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642286/h8l63pgueleelc1l7ey0.jpg",
    price: 200,
    rating: 4.0,
    description: "A selection of premium coffees from around the world.",
  },
  {
    id: "3",
    name: "Milk",
    category: "Dairy",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642410/cub14vzlwbwimoqefsre.jpg",
    price: 100,
    rating: 3.5,
    description: "Fresh, organic milk straight from the farm.",
  },
  {
    id: "4",
    name: "Avocado Oil",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642286/rhdkwyzubviwgx2pebyc.jpg",
    price: 50,
    rating: 4.2,
    description: "Cold-pressed avocado oil for healthy cooking.",
  },
  {
    id: "5",
    name: "Natural Extracted Edible Oil",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642291/hu9cy3oerjczybkjo9ha.jpg",
    price: 250,
    rating: 4.7,
    description: "Pure, natural extracted oil for all your cooking needs.",
  },
  {
    id: "6",
    name: "Handwash",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642290/hkusxv5usczmb2mc9jhh.jpg",
    price: 150,
    rating: 4.3,
    description: "Gentle handwash with a refreshing fragrance.",
  },
  {
    id: "7",
    name: "Cheese",
    category: "Dairy",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642409/rttbg0csezps15aszbmy.jpg",
    price: 350,
    rating: 4.6,
    description: "Rich, creamy farm-made cheese for every meal.",
  },
  {
    id: "8",
    name: "Almonds",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642285/js0cljeuenndzss77n8x.jpg",
    price: 300,
    rating: 4.8,
    description: "Healthy and crunchy organic almonds for snacking.",
  },
  {
    id: "9",
    name: "Body Lotion",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642316/mcclratcoedlt9x3gfry.jpg",
    price: 180,
    rating: 4.4,
    description: "Nourishing body lotion for soft, moisturized skin.",
  },
  {
    id: "10",
    name: "Yogurt",
    category: "Dairy",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642410/e1kbari4cj6atz4ife5u.jpg",
    price: 120,
    rating: 4.1,
    description: "Creamy, probiotic-rich yogurt for a healthy diet.",
  },
  {
    id: "11",
    name: "Corn Flakes",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642288/pcehjg3jxbzniqpcpiak.jpg",
    price: 450,
    rating: 4.6,
    description: "Crispy and delicious corn flakes for breakfast.",
  },
  {
    id: "12",
    name: "Face Wash",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642292/zelws2cjxkbnsrrvt6vv.jpg",
    price: 60,
    rating: 4.2,
    description: "Gentle face wash to keep your skin clean and fresh.",
  },
  {
    id: "13",
    name: "Butter",
    category: "Dairy",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642409/jpifakqvfivi9drapwwb.jpg",
    price: 200,
    rating: 4.4,
    description: "Rich, creamy butter for your toast and baking needs.",
  },
  {
    id: "14",
    name: "Chia Seeds",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642287/b9vv2keut17fsjgvwvu4.jpg",
    price: 300,
    rating: 4.7,
    description: "Nutritious organic chia seeds for smoothies and baking.",
  },
  {
    id: "15",
    name: "Green Chilli",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642443/uqynrlrfso9c29yme761.jpg",
    price: 100,
    rating: 4.3,
    description: "Spicy fresh green chillies for your favorite dishes.",
  },
  {
    id: "16",
    name: "Peanut Butter",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642292/fnrmvr8rt7u4buhyryqe.png",
    price: 350,
    rating: 4.8,
    description: "Creamy, natural peanut butter for spreads and cooking.",
  },
  {
    id: "17",
    name: "Hand Sanitizer",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642290/h8ucjnabesk0erwa8m67.jpg",
    price: 550,
    rating: 4.9,
    description: "Antibacterial hand sanitizer to keep germs at bay.",
  },
  {
    id: "18",
    name: "Hersheys",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642291/m05geuvmgzeafpdidlqr.jpg",
    price: 80,
    rating: 4.2,
    description: "Rich, creamy Hersheys chocolate syrup for desserts.",
  },
  {
    id: "19",
    name: "Ketchup",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642290/rpbiwn0ix3cbttglihei.jpg",
    price: 750,
    rating: 4.6,
    description: "Tangy tomato ketchup to enhance the taste of your food.",
  },
  {
    id: "20",
    name: "Khajoor",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642291/uokchuublalyz4e2taif.webp",
    price: 150,
    rating: 4.7,
    description: "Sweet, organic dates rich in nutrients.",
  },
  {
    id: "21",
    name: "Masoor Dal",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642291/zdvmxur1b7mtclv8hilv.jpg",
    price: 100,
    rating: 4.7,
    description: "Nutritious and protein-rich Masoor dal.",
  },
  {
    id: "22",
    name: "Moong Dal",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642292/tfn9ttb7qnngwsb2fc9v.jpg",
    price: 200,
    rating: 4.7,
    description: "Healthy and organic Moong dal for a protein-rich diet.",
  },
  {
    id: "23",
    name: "Oats",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642293/qetne30opvqphuqwc80s.jpg",
    price: 250,
    rating: 4.7,
    description: "Whole grain oats for a healthy and filling breakfast.",
  },
  {
    id: "24",
    name: "Salt",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642291/ychfjvzzsyqgigtnaotk.jpg",
    price: 30,
    rating: 4.7,
    description: "Pure, fine salt to enhance the flavor of your meals.",
  },
  {
    id: "25",
    name: "Shampoo",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642292/nmysqyybf8u4qe0m4pum.jpg",
    price: 120,
    rating: 4.7,
    description: "Gentle shampoo for daily hair care.",
  },
  {
    id: "26",
    name: "Soap",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642292/bvpgdjm9xxrd6hqj1nzo.jpg",
    price: 80,
    rating: 4.7,
    description: "Natural, organic soap for soft and clean skin.",
  },
  {
    id: "27",
    name: "Tea",
    category: "Grocery",
    image: "/grocery/Tea.jpeg",
    price: 200,
    rating: 4.7,
    description: "Refreshing and aromatic tea leaves for a relaxing brew.",
  },
  {
    id: "28",
    name: "Toor Dal",
    category: "Grocery",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642293/oimttgbxykm1lvfjzwyq.jpg",
    price: 100,
    rating: 4.7,
    description: "Organic Toor dal, perfect for protein-packed meals.",
  },
];


// Expanded Juice Data (20 items)
export const juices: Product[] = [
  {
    id: "1",
    name: "Apple Juice",
    category: "Fruits",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642317/vt9uy6xknvvuju2vd7jt.jpg",
    price: 500,
    rating: 4.5,
    description: "Freshly pressed apple juice.",
  },
  {
    id: "2",
    name: "Banana Juice",
    category: "Fruits",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642333/fuapjvuhrwgwkgrolgyt.jpg",
    price: 200,
    rating: 4.0,
    description: "Delicious banana juice made from ripe bananas.",
  },
  {
    id: "3",
    name: "Carrot Juice",
    category: "Vegetables",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642322/dd9yezcttxlcrlayeszn.jpg",
    price: 150,
    rating: 4.1,
    description: "Nutritious carrot juice packed with vitamins.",
  },
  {
    id: "4",
    name: "Orange Juice",
    category: "Fruits",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642323/d9qe1j0gpg5wekhcuual.webp",
    price: 350,
    rating: 4.7,
    description: "Freshly squeezed orange juice.",
  },
  {
    id: "5",
    name: "Mango Juice",
    category: "Fruits",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642372/lsr7nz1lncfwsgm4ei1l.jpg",
    price: 400,
    rating: 4.6,
    description: "Sweet and refreshing mango juice.",
  },
  {
    id: "6",
    name: "Pineapple Juice",
    category: "Fruits",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642322/wacmx9daooivt4gtfa6x.jpg",
    price: 300,
    rating: 4.5,
    description: "Tropical and tangy pineapple juice.",
  },
  {
    id: "7",
    name: "Mixed Berry Juice",
    category: "Fruits",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642321/aozeae66x2nr8uhb1seb.jpg",
    price: 450,
    rating: 4.8,
    description: "A blend of fresh berries in a delicious juice.",
  },
  {
    id: "8",
    name: "Grape Juice",
    category: "Fruits",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642320/ersjsq5emgd8vhu1judy.jpg",
    price: 400,
    rating: 4.4,
    description: "Rich and flavorful grape juice.",
  },
  {
    id: "9",
    name: "Watermelon Juice",
    category: "Fruits",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642325/dvs2m7djaebzdi70pgbw.jpg",
    price: 300,
    rating: 4.7,
    description: "Refreshing watermelon juice, perfect for summer.",
  },
  {
    id: "10",
    name: "Pomegranate Juice",
    category: "Fruits",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642324/bpx751avltxbcxa2tngl.jpg",
    price: 550,
    rating: 4.9,
    description: "Antioxidant-rich pomegranate juice.",
  },
  {
    id: "11",
    name: "Lemon Juice",
    category: "Fruits",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642319/ebslbyolrthbnhf7dlrc.jpg",
    price: 100,
    rating: 4.3,
    description: "Freshly squeezed lemon juice, great for drinks.",
  },
  {
    id: "12",
    name: "Tomato Juice",
    category: "Vegetables",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642325/askzinvuw2dushdekhdw.jpg",
    price: 180,
    rating: 4.1,
    description: "Nutritious tomato juice full of flavor.",
  },
  {
    id: "13",
    name: "Beetroot Juice",
    category: "Vegetables",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642318/ieqmkjuiayznmlzyopxu.jpg",
    price: 250,
    rating: 4.6,
    description: "Rich and healthy beetroot juice.",
  },
  {
    id: "14",
    name: "Cucumber Juice",
    category: "Vegetables",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642318/lv9ibtxm6x9k5qahfcfa.jpg",
    price: 140,
    rating: 4.2,
    description: "Refreshing and cooling cucumber juice.",
  },
  {
    id: "15",
    name: "Guava Juice",
    category: "Fruits",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642319/sboeuohmalqmaxxpgqzc.jpg",
    price: 400,
    rating: 4.5,
    description: "Tropical and sweet guava juice.",
  },
  {
    id: "16",
    name: "Pear Juice",
    category: "Fruits",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642322/vowm2hu1nzahdvxoyhaw.jpg",
    price: 350,
    rating: 4.3,
    description: "Mildly sweet and smooth pear juice.",
  },
  {
    id: "17",
    name: "Papaya Juice",
    category: "Fruits",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642321/v51eiyxfysr5yjtf0fez.jpg",
    price: 300,
    rating: 4.1,
    description: "Creamy and rich papaya juice.",
  },
  {
    id: "18",
    name: "Kiwi Juice",
    category: "Fruits",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642324/jtnqteqz1gaxhe2hedgp.jpg",
    price: 450,
    rating: 4.4,
    description: "Tangy and exotic kiwi juice.",
  },
  {
    id: "19",
    name: "Cranberry Juice",
    category: "Fruits",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642317/ibe5kpluafc8dq3zonii.jpg",
    price: 500,
    rating: 4.8,
    description: "Tart and antioxidant-packed cranberry juice.",
  },
  {
    id: "20",
    name: "Tangerine Juice",
    category: "Fruits",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642324/qfq9zxom5gz7dctmchmc.jpg",
    price: 350,
    rating: 4.6,
    description: "Citrusy and tangy tangerine juice.",
  },
];

// Expanded Products Data (20 items)
export const products: Product[] = [
  {
    id: '1',
    name: 'Banana',
    category: 'Fruits',
    image: 'https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642275/cdvotgvlac9f8v56qomw.jpg',
    price: 82,
    rating: 4.5,
    originalPrice: 99,
    isOnSale: true,
    description: 'Fresh bananas full of nutrients, perfect for a quick snack. Only ₹82 per dozen.',
  },
  {
    id: "2",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642290/h8ucjnabesk0erwa8m67.jpg",
    category: "Grocery",
    name: "Hand Sanitizer",
    price: 150,
    rating: 3,
    description: "Keep your hands clean and germ-free. 500ml for ₹1250.",
  },
  {
    id: "3",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642443/uqynrlrfso9c29yme761.jpg",
    category: "Vegetables",
    name: "Handpicked Red Chillies",
    price: 60,
    rating: 5,
    description: "Spicy handpicked red chillies, perfect for adding heat to your dishes. 1kg for ₹1600.",
  },
  {
    id: "4",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642291/hu9cy3oerjczybkjo9ha.jpg",
    category: "Grocery",
    name: "Natural Extracted Edible Oil",
    price:750,
    originalPrice: 550,
    isOnSale: true,
    rating: 3,
    description: "Pure, naturally extracted oil for healthy cooking. 1 liter at ₹2100 (was ₹2850).",
  },
  {
    id: "5",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642447/g7jzvzmlszhevn53kip5.jpg",
    category: "Vegetables",
    name: "Potatoes",
    price: 40,
    rating: 4.7,
    description: "Fresh organic potatoes, direct from the farm. 5kg for ₹840.",
  },
  {
    id: "6",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642286/firpltvgwpoudojuopnt.jpg",
    category: "Grocery",
    name: "Basmati Rice",
    price: 850,
    rating: 4.8,
    description: "Premium long-grain basmati rice with a fragrant aroma. 5kg for ₹3360.",
  },
  {
    id: "7",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642409/cbmvnlhlnpo0d3vsgcfl.jpg",
    category: "Dairy",
    name: "Free Range Eggs",
    price: 420,
    rating: 4.6,
    description: "High-quality free-range eggs, perfect for a healthy breakfast. 12 eggs for ₹420.",
  },
  {
    id: "8",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642292/bvpgdjm9xxrd6hqj1nzo.jpg",
    category: "Grocery",
    name: "Soap",
    price: 1000,
    rating: 4.3,
    description: "Organic, chemical-free soap for gentle skincare. 1 bar for ₹1000.",
  },
  {
    id: "9",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642293/d92iklqciosblcmayczr.jpg",
    category: "Grocery",
    name: "Green Tea",
    price: 1680,
    rating: 4.9,
    description: "Refreshing and healthy green tea leaves. 250g for ₹1680.",
  },
  {
    id: "10",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642448/zfpd991g8n3szm07m0rh.jpg",
    category: "Vegetables",
    name: "Organic Tomatoes",
    price: 588,
    rating: 4.5,
    description: "Fresh organic tomatoes, perfect for salads and cooking. 1kg for ₹588.",
  },
  {
    id: "11",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642410/cub14vzlwbwimoqefsre.jpg",
    category: "Dairy",
    name: "Milk",
    price: 210,
    rating: 4.3,
    description: "Fresh organic milk from grass-fed cows. 1 liter for ₹210.",
  },
  {
    id: "12",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642446/embhjymnbtox7ndaig60.jpg",
    category: "Vegetables",
    name: "Palak",
    price: 252,
    rating: 4.8,
    description: "Fresh palak (spinach), rich in iron. 500g for ₹252.",
  },
  {
    id: "13",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642287/b9vv2keut17fsjgvwvu4.jpg",
    category: "Grocery",
    name: "Chia Seeds",
    price: 420,
    rating: 4.9,
    description: "Nutrient-rich chia seeds for a healthy diet. 200g for ₹420.",
  },
  {
    id: "14",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642445/gbkclw5m2e7yv8gafarn.jpg",
    category: "Vegetables",
    name: "Lettuce",
    price: 168,
    rating: 4.6,
    description: "Crisp, fresh organic lettuce. 1 head for ₹168.",
  },
  {
    id: "15",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642409/l0fybkgtkxknykzgfvmw.jpg",
    category: "Dairy",
    name: "Almond Milk",
    price: 252,
    rating: 4.5,
    description: "Nutritious and creamy almond milk. 1 liter for ₹252.",
  },
  {
    id: "16",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642293/rwyjeygqetsccd73g5ch.jpg",
    category: "Grocery",
    name: "Whole Wheat Pasta",
    price: 336,
    rating: 4.2,
    description: "Healthy whole wheat pasta for a delicious meal. 500g for ₹336.",
  },
  {
    id: "17",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642288/skilnruozt6s2rxohvvj.jpg",
    category: "Grocery",
    name: "Extra Virgin Olive Oil",
    price: 840,
    rating: 4.7,
    description: "Premium cold-pressed extra virgin olive oil. 500ml for ₹840.",
  },
  {
    id: "18",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642448/cklixhsjexmv4cfnr0lj.jpg",
    category: "Vegetables",
    name: "Pumpkin",
    price: 252,
    rating: 4.4,
    description: "Fresh, sweet organic pumpkin. 1kg for ₹252.",
  },
  {
    id: "19",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642287/ka8bxmam5ej9jt5wjiyy.jpg",
    category: "Grocery",
    name: "Organic Brown Sugar",
    price: 420,
    rating: 4.6,
    description: "Rich and flavorful organic brown sugar. 1kg for ₹420.",
  },
  {
    id: "20",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642275/x8nnw0k9eyb0bth8un1g.jpg",
    category: "Fruits",
    name: "Fresh Mangoes",
    price: 252,
    rating: 4.9,
    description: "Juicy and ripe fresh mangoes. 1kg for ₹252.",
  },
  {
    id: "21",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642275/jm61wfdo2g9vqkbtuz45.jpg",
    category: "Fruits",
    name: "Black Grapes",
    price: 252,
    rating: 4.9,
    description: "Sweet, fresh black grapes. 1kg for ₹252.",
  },
  {
    id: "22",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642276/sfyo1smlzdb4o2bb72ox.jpg",
    category: "Fruits",
    name: "Watermelon",
    price: 252,
    rating: 4.9,
    description: "Fresh, juicy watermelon. 1kg for ₹252.",
  },
  {
    id: "23",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642275/opkpqazsmx2amevt2kd9.jpg",
    category: "Fruits",
    name: "Grapes",
    price: 252,
    rating: 4.9,
    description: "Fresh, juicy grapes. 1kg for ₹252.",
  },
  {
    id: "24",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642276/e20nprldh56fq52xkyzv.jpg",
    category: "Fruits",
    name: "Oranges",
    price: 252,
    rating: 4.9,
    description: "Fresh, sweet oranges. 1kg for ₹252.",
  },
  {
    id: "25",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642276/pq5jhnkwgnqwey4ajoie.jpg",
    category: "Fruits",
    name: "Pineapple",
    price: 252,
    rating: 4.9,
    description: "Fresh, sweet pineapples. 1 whole pineapple for ₹252.",
  },
  {
    id: "26",
    image: "https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642275/m3jl323mqmiuxreqpkvn.jpg",
    category: "Fruits",
    name: "Apples",
    price: 252,
    rating: 4.9,
    description: "Crisp, fresh apples. 1kg for ₹252.",
  },
];


// Category definitions remain the same
interface Category {
  id: string;
  name: 'Fruits' | 'Vegetables' | 'Groceries';
  image: string;
  description?: string;
}

export const categories: Category[] = [
  {
      id: '1',
      name: 'Fruits',
      image: 'https://res.cloudinary.com/dojpvlfnu/image/upload/v1726658561/xgiyukrwha7tnn9pif4w.jpg',
      description: 'Fresh and organic fruits'
  },
  {
      id: '2',
      name: 'Vegetables',
      image: 'https://res.cloudinary.com/dojpvlfnu/image/upload/v1726642459/ykiigc2m8trpovntjhlu.jpg',
      description: 'Organic and farm-fresh vegetables'
  },
  {
      id: '3',
      name: 'Groceries',
      image: 'https://res.cloudinary.com/dojpvlfnu/image/upload/v1726658654/vw8kpzstabgizabmwejt.jpg',
      description: 'All your grocery needs'
  }
];
